### ISSUE TITLE
Update doc

### ISSUE THREAD

**Issue by storytime** [enonic/starter-vanilla#1]
http://xp.readthedocs.org/en/stable/tutorials/my-first-app/initialize-project.html

[$XP_INSTALL]/toolbox/toolbox.sh init-project -n com.company.myapp -r starter-vanilla -c 1.0.0

I assume that "-c" is not valid.

http://i.imgur.com/tVNmhsv.png

**Comment by Michael-Lazell** [comment]
The -c only works on XP version 6.4. It allows you to checkout a specific release version of the app that you are copying. 6.4 is out now and it has a lot of improvements so I suggest you use it instead of 6.3.

**Comment by storytime** [comment]
Yes, 6.3
