### ISSUE TITLE
Add .gitignore

### ISSUE THREAD

**Issue by selbekk** [enonic/starter-vanilla#4]
Can the starter please add a `.gitignore` file that ignores the stuff that doesn't need to be included in version control?

**Comment by torlokken** [comment]
It should already exist, do you miss anything here? https://github.com/enonic/starter-vanilla/blob/master/.gitignore

**Comment by selbekk** [comment]
Oops, that's right. However, I think the [`init-project`](https://github.com/enonic/xp/blob/master/modules/tools/toolbox/src/main/java/com/enonic/xp/toolbox/app/InitAppCommand.java) command removes it when cloning down the project.

**Comment by selbekk** [comment]
More specifically, [this line](https://github.com/enonic/xp/blob/master/modules/tools/toolbox/src/main/java/com/enonic/xp/toolbox/app/InitAppCommand.java#L186) skips `.gitignore` and `.gitkeep` files specifically. Should probably be removed, no?

**Comment by Bellfalasch** [comment]
This has been removed from the init-project code now =) Issue can be closed @torlokken
